### ISSUE TITLE
Autoaugment Error

### ISSUE THREAD

**Issue by SiBensberg** [google/automl#1091]

**Comment by Steve-2040** [comment]
Hi @SiBensberg I had errors when training using autoaugment v0 on TPU (tf-version=2.6.0):
```tensorflow.python.framework.errors_impl.InvalidArgumentError:  output dimensions must be positive```
Commenting out the 'Cutout' in (efficientdet/aug/autoaugment.py) solved the problem for me and training continue with the rest of the augmentation options:
``` Python
 policy = [
      [('TranslateX_BBox', 0.6, 4), ('Equalize', 0.8, 10)],
      #[('TranslateY_Only_BBoxes', 0.2, 2), ('Cutout', 0.8, 8)],
      [('Sharpness', 0.0, 8), ('ShearX_BBox', 0.4, 0)],
      [('ShearY_BBox', 1.0, 2), ('TranslateY_Only_BBoxes', 0.6, 6)],
      [('Rotate_BBox', 0.6, 10), ('Color', 1.0, 6)],
  ]
```
My config file:
```yaml
num_classes: 5
label_map: {1: name1, 2: name2, 3: name3, 4: name4}
max_instances_per_image: 20
regenerate_source_id: True
image_size: 1280x1024
aspect_ratios: [0.1, 0.26, 0.5, 1.33] # ratio w/h: e.g. w=1.4, h=0.7 is 2.0
jitter_min: 0.8
jitter_max: 1.4
autoaugment_policy: v0
```

I have not investigated it further. It looks like in my case, 'Cutout' wrongly calculate the bbox coordinates?  Hope this helps.
